generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true

    config:
      fields:
        password_again: { label: "Password (confirm)" }
        created_at: { date_format: yyyy/MM/dd hh:mm:ss }

      list:
        title:   Danh sách Người sử dụng
        display: [=username, email_address, _userType, created_at, updated_at, last_login]

      form:
        class: sfGuardUserAdminForm
        display:
          "Thông tin chung": [first_name, last_name, email_address, username, password, password_again]
          "Phân quyền": [is_active, is_super_admin]

      edit:
        title: Sửa thông tin Người sử dụng "%%username%%"

      new:
        title: Tạo mới Người sử dụng

      filter:
        class: false