generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Task
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Task
    plural:                Tasks
    route_prefix:          task
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      
      fields:
        created_at:
          label: Ngày tạo
          #help: Fill in the article body
          #attributes: { class: foo }
          date_format: yyyy/MM/dd hh:mm:ss 
        reminder_email1:
          label: Email thông báo 1
          help: Địa chỉ email để gửi cảnh báo nếu task bị chậm lần 1
          attributes: { class: foo }
          
      list:    
        #layout:  stacked # View all data on one cell
        title: "Công việc"
        display: [=task_name, user_id, task_description, created_at, assigned_to]
        sort: [piriority, asc]
        max_per_page:  20
      
      filter:
        class: false
        
      form: ~
#        display: 
#          "Thông tin công việc": [task_name, task_description, piriority]
#          "Giao việc": [assigned_to, remind_1st_at]
      edit:    
        title: "Xem công việc: %%task_name%%"
      
      new:     ~