default:
  layout: layout
  theme: admin
  components:
    sidebar: [leftpanel, task]
  javascripts: 
    - jquery/jquery-1.8.0.min.js
    - jquery/jquery-ui-1.8.23.custom.min.js
  stylesheets:
    - jquery_ui/jquery-ui-1.8.23.custom.css
    
viewCommentSuccess:
  layout: layout
  theme: admin
  non_verbose_templates: true
  stylesheets: 
    - style.css
    - reset.css
    - text.css
    - layout.css
    - nav.css
    - grid.css
    - formalize.css
    - main.css
    - admin_default.css
reminderPopupSuccess:
  layout: layoutNoNav
  