Task:
  actAs:
    Timestampable:
    SoftDelete:
      name: is_deleted
      type: boolean
  columns:
    user_id:
      type: integer
      notnull: true
      default: 1
    task_name:
      type: string(500)
      notnull: true
    task_description:
      type: string
    piriority:
      type: integer
      notnull: true
      default: 1
    assigned_to:
      type: string(500)
      notnull: false
    reminded_count:
      type: integer
      notnull: true
      default: 0
    remind_1st_at:
      type: timestamp(25)
      notnull: false
    remind_2rd_at:
      type: timestamp(25)
      notnull: false
    remind_3th_at:
      type: timestamp(25)
      notnull: false
    reminder_email1:
      type: string(250)
      notnull: false
    reminder_email2:
      type: string(250)
      notnull: false
    completed_by:
      type: string(250)
      notnull: false
    completed_at:
      type: timestamp(25)
      notnull: false
      
  relations:
    User:
      class: sfGuardUser
      local: user_id