Task:
  actAs:
    Timestampable:
    SoftDelete:
      name: is_deleted
      type: boolean
  columns:
    user_id:
      type: integer
      notnull: true
    task_name:
      type: string(150)
      notnull: true
    task_description:
      type: string
    priority:
      type: integer
      notnull: true
      default: 1
    assigned_to:
      type: string(100)
      notnull: false
    reminded_count:
      type: integer
      notnull: true
      default: 0
    remind_1st_at:
      type: timestamp(25)
      notnull: false
    remind_2rd_at:
      type: timestamp(25)
      notnull: false
    remind_3th_at:
      type: timestamp(25)
      notnull: false
    reminder_email1:
      type: string(250)
      notnull: false
    reminder_email2:
      type: string(250)
      notnull: false
    completed_by:
      type: string(250)
      notnull: false
    completed_at:
      type: timestamp(25)
      notnull: false
      
  relations:
    User:
      class: sfGuardUser
      local: user_id
      
#    TaskComments:
#      class: TaskComment
#      foreignAlias: TaskComments
#      foreign: task_id
#      local: id
#      type: one
#      foreignType: many
      
  options:
    orderBy: created_at DESC
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
    
TaskComment:
  actAs:
    Timestampable:
  columns:
    task_id:
      type: integer
      notnull: true
    user_id:
      type: integer
      notnull: true
    comment:
      type: string(500)
      notnull: true
    can_view:
      type: boolean
      notnull: false
      
  relations:
    User:
      class: sfGuardUser
      local: user_id
      
    Task:
      foreignAlias: TaskComments
      local: task_id
      foreign: id
      type: one
      foreignType: many
      
  options:
    orderBy: created_at DESC
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8