<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/12/17 11:19:02
sfConfig::add(array(
  'app_website_name' => 'Diamond Bay Resort',
  'app_website_base_url' => 'http://reminider.local',
  'app_emails_dont_reply' => 'admin@diamond.com',
  'app_emails_reminder_subject' => 'Công việc cần hoàn thành ngay',
  'app_sf_guard_plugin_routes_register' => false,
  'app_reminder_1st_after' => 10,
  'app_reminder_2rd_after' => 15,
  'app_reminder_3th_after' => 15,
  'app_reminder_email1' => 'anld@isoftco.com',
  'app_reminder_email2' => 'anld.agrib@gmail.com',
));
