<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('task', 'follow_user_id', 'integer', '8', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('task', 'follow_user_id');
    }
}