<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('task_comment', 'can_view', 'boolean', '25', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('task_comment', 'can_view');
    }
}