all:
  mailer:
    class: sfMailer
    param:
      logging: true           #%SF_LOGGING_ENABLED%
      charset: utf-8          #%SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host: mail.diamondbayresort.vn
          port: 25
          encryption: ~
          username: dbreminder@diamondbayresort.vn
          password: db@re
