all:
  mailer:
    class: sfMailer
    param:
      logging: true           #%SF_LOGGING_ENABLED%
      charset: utf-8          #%SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host: smtp.gmail.com
          port: 465
          encryption: ssl
          username: bounced.bob@gmail.com
          password: bouncybouncy
