<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/12/20 11:38:30
sfConfig::add(array(
  'app_website_name' => 'Diamond Bay Resort',
  'app_website_base_url' => 'http://reminider.local',
  'app_emails_dont_reply' => 'dbreminder@diamondbayresort.vn',
  'app_emails_reminder_subject' => 'Công việc cần hoàn thành ngay',
  'app_sf_guard_plugin_routes_register' => false,
  'app_reminder_1st_after' => 10,
  'app_reminder_2rd_after' => 15,
  'app_reminder_3th_after' => 15,
  'app_reminder_email1' => 'hienpc@ymail.com',
  'app_reminder_email2' => 'hienpc@ymail.com',
  'app_task_prioryties' => array (
  1 => 'Không gấp',
  2 => 'Bình thường',
  3 => 'Cần sớm',
  4 => 'Gấp',
  5 => 'Khẩn cấp',
),
));
