<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/12/12 11:22:57
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_reminder_1st_after' => 10,
  'app_reminder_email2' => 'anld.agrib@gmail.com',
));
