<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/10 16:21:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=reminder',
  'username' => 'root',
  'password' => '123456',
  'name' => 'doctrine',
)),);
