<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/14 06:34:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=task_reminder',
  'username' => 'root',
  'password' => '123456',
  'name' => 'doctrine',
)),);
