<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/12/19 14:01:14
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_reminder_1st_after' => 10,
  'app_reminder_2rd_after' => 15,
  'app_reminder_3th_after' => 15,
  'app_reminder_email1' => 'anld@isoftco.com',
  'app_reminder_email2' => 'anld.agrib@gmail.com',
  'app_task_prioryties' => array (
  1 => 'Không gấp',
  2 => 'Bình thường',
  3 => 'Cần sớm',
  4 => 'Gấp',
  5 => 'Khẩn cấp',
),
));
