<?php

/**
 * TaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object TaskTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Task');
    }

    /***
     * 
     */
    public function getTaskNeedRemindedOnTime($nowTime) {
        $query = Doctrine_Query::create()
                ->select('*')
                ->from('Task')
                ->where('is_deleted=0 AND completed_at IS NULL')
                ->addWhere("(DATE_FORMAT(remind_1st_at, '%Y-%m-%d %H:%i') = ?)
                    OR (DATE_FORMAT(remind_2rd_at, '%Y-%m-%d %H:%i') = ?)
                    OR (DATE_FORMAT(remind_3th_at, '%Y-%m-%d %H:%i') = ?)", 
                        array($nowTime, $nowTime, $nowTime))
                ->orderBy('priority DESC')
        ;
        return $query->execute();
    }

}