<?php

/**
 * TaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object TaskTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Task');
    }

    /***
     * 
     */
    private function createQueryForReminderOnTime($nowTime = '', $userId = 0) {
        $query = Doctrine_Query::create()
                ->select('*')
                ->from('Task')
                ->where('is_deleted=0 AND completed_at IS NULL')
                ->addWhere("DATE_FORMAT(created_at, '%Y/%m/%d') = ?", date('Y/m/d'))
                ->addWhere("(DATE_FORMAT(remind_1st_at, '%Y-%m-%d %H:%i') = ?)
                    OR (DATE_FORMAT(remind_2rd_at, '%Y-%m-%d %H:%i') = ?)
                    OR (DATE_FORMAT(remind_3th_at, '%Y-%m-%d %H:%i') = ?)", 
                        array($nowTime, $nowTime, $nowTime))
                ->orderBy('priority DESC')
        ;
        if($userId){
            $query->addWhere('user_id = ?', $userId);
        }
        return $query;
    }
    /***
     * 
     */
    public function findTaskNeedRemindedOnTime($nowTime, $userId = 0) {
        $query = $this->createQueryForReminderOnTime($nowTime, $userId);
        return $query->execute();
    }

    /***
     * 
     */
    public function countTaskNeedRemindedOnTime($nowTime, $userId = 0) {
        $query = $this->createQueryForReminderOnTime($nowTime, $userId);
        return $query->count();
    }
}